# This is a basic workflow that is manually triggered

name: TEST / Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ github.event.inputs.name }}"
        echo ${{ secrets.GITHUB_TOKEN }}
        go version
        echo "GITHUB_REF=${GITHUB_REF}"
        echo ${{ github.base_ref }}
        echo ${{ github.ref }}
        echo ${{ github.head_ref }}
