name: MergedBranchTest

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  merge-test:
    if: (github.event.pull_request.merged == true) && ("startsWith(github.event.pull_request.head.ref, 'test-*')")
    runs-on: ubuntu-latest
    steps:
      - name: test merge
        run: |
          echo "target branch was merged"
