name: MergedBranchTest

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tag:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  tag-test:
    runs-on: ubuntu-latest
    steps:
      - name: test merge
        run: |
          echo "tagged"

  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create simple description #TODO another version
        run: |
          echo "Commits: " > changelog.txt
          #find previos tag
          start_tag=$(git for-each-ref refs/tags/ --count=2 --sort=-version:refname --format='%(refname:short)' | awk 'NR==2')
          if [[ -n "${start_tag}"" ]]; then
            git log ${start_tag}...${{ github.ref }} --pretty=format:"  %s" >> changelog.txt
          else
            git log --pretty=format:"  %s" >> changelog.txt # first tag
          fi
          cat changelog.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.txt
          draft: true
          prerelease: false
