name: MergedBranchTest

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tag:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  tag-test:
    runs-on: ubuntu-latest
    steps:
      - name: test merge
        run: |
          echo "tagged"
